name: fe_flutter
description: Frontend POS Senja & Rona
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  esc_pos_utils_plus: ^2.0.3
  flutter_blue_plus: ^1.31.15
  path_provider: ^2.1.2
  dio: ^5.4.0
  permission_handler: ^11.3.0
  open_filex: ^4.4.0
  printing: ^5.12.0
  print_bluetooth_thermal: ^1.1.0

  flutter:
    sdk: flutter

  provider: ^6.0.5
  http: ^1.2.0
  mobile_scanner: ^4.0.1
  fl_chart: ^0.66.2
  file_picker: ^10.3.8
  pdf: ^3.10.7

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
